<a href="https://colab.research.google.com/github/roannarum/Data-Practice/blob/main/Sistem_Rekomendasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_excel('/content/RecSys.xlsx')
data

In [ ]:
# data preparation
data.info()

In [6]:
# menghitung similaritas dengan pearson correlation, corr kalo di python nilainya terbalik
import numpy as np
# iloc mengambil data berdasarkan index
x = np.array(data.iloc[0,1:9])
y = np.array(data.iloc[1,1:9])

In [8]:
import scipy
from scipy import stats

sim = scipy.stats.pearsonr(x,y)
# mengambil nilai korelasinya saja yaitu r nya
print("similaritas aleysa dan user1 = ",sim[0])

similaritas aleysa dan user1 =  0.5369248441712194

In [9]:
Pearson = []
Pearson = data
Pearson['similarity'] = 1 #membuat kolom baru untuk menyimpan nilainya

x = np.array(data.iloc[0,1:9])

for i in range(1, len(Pearson)):
    y = np.array(data.iloc[i,1:9])
    sim = scipy.stats.pearsonr(x,y)
    sim = sim[0]
    Pearson.iloc[i:,10] = sim #memasukan data ke kolom baru

In [10]:
Pearson

,User,Film1,Film2,Film3,Drama1,Drama2,Drama3,Comedy1,Comedy2,Comedy3,similarity
0,Alesya,3.0,4.0,2.0,1.0,2.0,1.0,3.0,5.0,NaN,1.000000
1,User1,2.0,5.0,1.0,1.0,3.0,4.0,4.0,4.0,2.0,0.536925
2,User2,5.0,4.0,2.0,4.0,1.0,1.0,5.0,1.0,3.0,0.091213
3,User3,3.0,4.0,2.0,2.0,1.0,2.0,5.0,1.0,4.0,0.179374
4,User4,1.0,3.0,1.0,5.0,2.0,4.0,4.0,2.0,1.0,-0.392090
5,User5,2.0,2.0,1.0,3.0,3.0,1.0,3.0,3.0,1.0,0.314800
6,User6,5.0,1.0,1.0,2.0,4.0,1.0,2.0,4.0,5.0,0.348025
7,User7,2.0,1.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,-0.427121
8,User8,3.0,1.0,4.0,1.0,4.0,2.0,1.0,1.0,5.0,-0.346036
9,User9,4.0,5.0,2.0,4.0,5.0,1.0,2.0,5.0,3.0,0.537856
10,User10,1.0,3.0,5.0,3.0,1.0,2.0,2.0,5.0,5.0,0.336918
11,User11,2.0,2.0,5.0,2.0,4.0,3.0,4.0,3.0,2.0,-0.146438
12,User12,4.0,2.0,1.0,1.0,2.0,3.0,5.0,5.0,3.0,0.594759
13,User13,5.0,5.0,3.0,4.0,3.0,5.0,1.0,3.0,5.0,-0.153153
14,User14,5.0,4.0,2.0,5.0,1.0,3.0,4.0,1.0,3.0,-0.224000
15,User15,2.0,1.0,5.0,2.0,5.0,2.0,5.0,4.0,5.0,0.045596
16,User16,3.0,3.0,2.0,3.0,1.0,1.0,3.0,2.0,1.0,0.314800
17,User17,4.0,4.0,3.0,4.0,4.0,4.0,1.0,5.0,2.0,0.160183
18,User18,4.0,1.0,1.0,2.0,2.0,2.0,2.0,4.0,3.0,0.413728
19,User19,5.0,2.0,4.0,1.0,4.0,1.0,4.0,3.0,4.0,0.335578
20,User20,1.0,2.0,3.0,1.0,3.0,1.0,3.0,2.0,2.0,0.219199
21,User21,4.0,3.0,3.0,3.0,2.0,4.0,3.0,5.0,4.0,0.456881
22,User22,3.0,4.0,1.0,4.0,1.0,5.0,4.0,4.0,5.0,0.119332
23,User23,2.0,1.0,5.0,2.0,5.0,4.0,1.0,5.0,3.0,-0.091213
24,User24,5.0,4.0,1.0,3.0,1.0,5.0,5.0,2.0,2.0,-0.014475
25,User25,2.0,2.0,5.0,4.0,5.0,1.0,2.0,1.0,5.0,-0.471159
26,User26,3.0,2.0,1.0,5.0,2.0,2.0,5.0,4.0,2.0,0.134231
27,User27,5.0,4.0,3.0,5.0,5.0,3.0,2.0,2.0,3.0,-0.399264
28,User28,2.0,3.0,4.0,5.0,1.0,4.0,5.0,4.0,5.0,-0.107624
29,User29,1.0,3.0,3.0,3.0,2.0,1.0,2.0,5.0,2.0,0.581238
30,User30,4.0,1.0,3.0,3.0,5.0,5.0,5.0,3.0,4.0,-0.441441